import { CalendarClock, CheckCircle2, ChevronDown, ChevronUp, ImagePlus, Pencil, PlusCircle, RotateCw, ShieldCheck } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, Image, Modal, Pressable, StyleSheet, Text, View } from 'react-native';

import { AppScreen } from '@/components/layout/app-screen';
import { AppButton } from '@/components/ui/app-button';
import { Card } from '@/components/ui/card';
import { FormField } from '@/components/ui/form-field';
import { scheduledDraftSlots } from '@/data/promotions';
import { useAppData } from '@/state/app-data';
import { colors, fonts, radii, spacing, textStyles } from '@/theme/tokens';
import type { PromotionDraft, PromotionDraftStatus } from '@/types';

const statusLabel: Record<PromotionDraftStatus, string> = { 'Needs Photo': 'Needs Photo', 'Needs Revision / Not Published': 'Needs Revision', 'Waiting for Approval': 'For Approval', Approved: 'Approved', Published: 'Published', 'Failed to Publish': 'Retry Needed' };
const actions: Record<PromotionDraftStatus, { label: string; detail: string; button: string; icon: typeof CheckCircle2; disabled?: boolean }> = {
  'Waiting for Approval': { label: 'Ready to approve', detail: 'Photo and allocation checks are complete.', button: 'Approve', icon: CheckCircle2 },
  'Needs Photo': { label: 'Needs a real food photo', detail: 'Select or upload a photo before this draft can be approved.', button: 'Add Photo', icon: ImagePlus },
  'Needs Revision / Not Published': { label: 'Needs revision', detail: 'Availability changed before publishing.', button: 'Revise', icon: Pencil },
  Approved: { label: 'Approved', detail: 'Waiting for the scheduled publish attempt.', button: 'Approved', icon: ShieldCheck, disabled: true },
  Published: { label: 'Published', detail: 'No action needed unless the owner wants to make a new draft.', button: 'Published', icon: ShieldCheck, disabled: true },
  'Failed to Publish': { label: 'Retry needed', detail: 'Check the Facebook connection, then retry publishing.', button: 'Retry', icon: RotateCw },
};

export default function PromotionsScreen() {
  const { promotions, actOnPromotion, updatePromotion } = useAppData(); const [expanded, setExpanded] = useState<string[]>([]); const [editing, setEditing] = useState<PromotionDraft | null>(null); const [caption, setCaption] = useState('');
  const toggle = (id: string) => setExpanded((items) => items.includes(id) ? items.filter((value) => value !== id) : [...items, id]);
  const edit = (draft: PromotionDraft) => { setEditing(draft); setCaption(draft.caption); };
  const save = () => { if (!editing) return; updatePromotion(editing.id, { caption, status: editing.status === 'Published' ? 'Published' : 'Waiting for Approval', approval: 'Edited content requires approval again.' }); setEditing(null); };
  return <AppScreen>
    <Card style={styles.gap}><View style={styles.row}><CalendarClock color={colors.terracotta} size={18} /><Text style={styles.title}>Weekly schedule</Text></View><Text style={styles.note}>Default posting schedule: Tuesday, Wednesday, Thursday, and Friday at 11:00 AM.</Text>{scheduledDraftSlots.map((slot) => <View key={slot.day} style={styles.slot}><View style={styles.day}><Text style={styles.strong}>{slot.day}</Text><Text style={styles.note}>{slot.time}</Text></View><View style={styles.flex}><Text numberOfLines={1} style={styles.status}>{slot.status}</Text><Text numberOfLines={1} style={styles.note}>{slot.selectedItem}</Text></View></View>)}<AppButton compact icon={<PlusCircle color={colors.terracotta} size={17} />} label="Request Extra Draft" onPress={() => Alert.alert('Extra draft requested', 'A new draft request was added to this prototype workflow.')} variant="ghost" /></Card>
    {promotions.map((draft) => { const action = actions[draft.status]; const Icon = action.icon; const open = expanded.includes(draft.id); const canEdit = draft.status !== 'Published'; return <Card key={draft.id} style={styles.gap}><View style={styles.draftTop}><View style={styles.flex}><Text style={styles.id}>#{draft.id}</Text><Text style={styles.draftTitle}>{draft.title}</Text><Text style={styles.note}>{draft.selectedMenuItem} / {draft.format}</Text></View><Text style={[styles.badge, toneStyle(draft.status)]}>{statusLabel[draft.status]}</Text></View><View style={styles.preview}>{draft.image ? <Image source={draft.image} style={styles.image} /> : null}<Text numberOfLines={4} style={[styles.note, styles.flex]}>{draft.caption}</Text></View><View style={styles.actionInfo}><Icon color={colors.terracotta} size={17} /><View style={styles.flex}><Text style={styles.actionTitle}>{action.label}</Text><Text style={styles.note}>{action.detail}</Text></View></View><View style={styles.buttons}>{canEdit ? <View style={styles.flex}><AppButton compact label="Edit" onPress={() => edit(draft)} variant="ghost" /></View> : null}<View style={styles.flex}><AppButton compact disabled={action.disabled} label={action.button} onPress={() => actOnPromotion(draft.id)} /></View></View><Pressable onPress={() => toggle(draft.id)} style={styles.detailsToggle}><Text style={styles.toggleText}>{open ? 'Hide details' : 'Show details'}</Text>{open ? <ChevronUp color={colors.muted} size={17} /> : <ChevronDown color={colors.muted} size={17} />}</Pressable>{open ? <View style={styles.details}><Detail label="Photo" value={draft.photoState} /><Detail label="Availability" value={draft.availabilityCheck} /><Detail label="Approval" value={draft.approval} /><Detail label="Publish" value={draft.publishState} /><Detail label="Referral" value={draft.referralLink} /></View> : null}</Card>; })}
    <Modal animationType="slide" onRequestClose={() => setEditing(null)} transparent visible={Boolean(editing)}><View style={styles.overlay}><Card style={styles.modal}><Text style={textStyles.title}>Edit promotional caption</Text><Text style={styles.note}>Editing invalidates prior approval and returns the draft to review.</Text><FormField label="Caption" multiline onChangeText={setCaption} value={caption} /><View style={styles.buttons}><View style={styles.flex}><AppButton label="Cancel" onPress={() => setEditing(null)} variant="secondary" /></View><View style={styles.flex}><AppButton label="Save" onPress={save} /></View></View></Card></View></Modal>
  </AppScreen>;
}

function Detail({ label, value }: { label: string; value: string }) { return <Text style={styles.note}><Text style={styles.strong}>{label}:</Text> {value}</Text>; }
function toneStyle(status: PromotionDraftStatus) { if (status === 'Published') return { backgroundColor: colors.readySoft, color: colors.ready }; if (status === 'Waiting for Approval') return { backgroundColor: colors.terracotta, color: colors.card }; if (status === 'Needs Photo') return { backgroundColor: '#FFF8ED', color: colors.amberDark }; return { backgroundColor: colors.dangerSoft, color: colors.terracotta }; }

const styles = StyleSheet.create({
  gap: { gap: spacing.md }, row: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, title: { color: colors.ink, fontFamily: fonts.extraBold, fontSize: 14 }, note: { ...textStyles.tiny }, strong: { color: colors.ink, fontFamily: fonts.extraBold }, slot: { backgroundColor: colors.menuSoft, borderRadius: radii.md, flexDirection: 'row', gap: spacing.md, padding: spacing.md }, day: { width: 92 }, flex: { flex: 1 }, status: { color: colors.terracotta, fontFamily: fonts.extraBold, fontSize: 12 },
  draftTop: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md }, id: { color: `${colors.terracotta}BB`, fontFamily: fonts.extraBold, fontSize: 12 }, draftTitle: { ...textStyles.title, marginTop: spacing.xs }, badge: { borderRadius: radii.sm, fontFamily: fonts.extraBold, fontSize: 11, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 5 }, preview: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md }, image: { borderRadius: radii.md, height: 74, width: 82 }, actionInfo: { alignItems: 'flex-start', backgroundColor: colors.menuSoft, borderRadius: radii.md, flexDirection: 'row', gap: spacing.sm, padding: spacing.md }, actionTitle: { color: colors.ink, fontFamily: fonts.extraBold, fontSize: 13 }, buttons: { flexDirection: 'row', gap: spacing.sm }, detailsToggle: { alignItems: 'center', borderColor: colors.line, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 44, paddingHorizontal: spacing.md }, toggleText: { color: colors.muted, fontFamily: fonts.extraBold, fontSize: 12 }, details: { borderTopColor: colors.line, borderTopWidth: 1, gap: spacing.sm, paddingTop: spacing.md },
  overlay: { backgroundColor: 'rgba(36,25,23,0.45)', flex: 1, justifyContent: 'flex-end', padding: spacing.lg }, modal: { gap: spacing.lg, marginBottom: spacing.lg },
});
